### ISSUE TITLE
What is the reason to have this delay PUT_METHOD_STEP_DELAY_MILLIS?

### ISSUE THREAD

**Issue by konstantinvlasenko** [carlnordenfelt/aws-api-gateway-for-cloudformation#15]
https://github.com/carlnordenfelt/aws-api-gateway-for-cloudformation/blob/a0bac09d7de63af77be7a99b9e2c1e025fd3facb/lib/service/ApiMethod/ApiMethodService.js#L12

**Comment by carlnordenfelt** [comment]
Hi!

That is a relevant question.

There have been issues in the past from time to time where AWS has responded with ConcurrentModificationsException while executing these operations. After long discussions with AWS where they ensured that each API call will complete its actions on their end before responding the only advice they had was to add a delay between the operations. Since adding this I don't think this problem has occurred again.

I should perhaps write a comment about this in the code.

/ Carl

**Comment by konstantinvlasenko** [comment]
Hi,
Thank you for clarification. I am actually went trough your code because of this issue https://forums.aws.amazon.com/thread.jspa?threadID=226162&tstart=0 when in AWS Console I see the Region: **undefined** inside** Integration Request **tile.
![error](https://cloud.githubusercontent.com/assets/404717/13322305/dab7901e-dba1-11e5-85de-da0c403ed65d.png)

**Comment by carlnordenfelt** [comment]
Interesting. 
I've never reflected over the fact that you don't have to specify in which region the lambda is running.
I just checked a method created with this project and Lambda Region is set to eu-west-1. 
That value must come either from the fact that my SDK is configured with region = eu-west-1 or extrapolated internally by AWS using the Lambda ARN.
It would be interesting to know where they take it from.

I take it it's ok to close this issue?

**Comment by konstantinvlasenko** [comment]
Yes. It should be closed.
