### ISSUE TITLE
Can you clarify the problems with updating from nodejs to nodejs4.3? 

### ISSUE THREAD

**Issue by jordie23** [carlnordenfelt/aws-api-gateway-for-cloudformation#53]
Hi,

AWS has given notice that they will be deprecating `nodejs` for lambda and so we need to update any functions that are currently using it.

In your documentation it currently says:

> Do not update the NodejsRuntime to nodejs4.3 on existing installations as this will break your APIs. Only use nodejs4.3 for new installations.

Could you clarify what issues will occur if we attempt this?

**Comment by carlnordenfelt** [comment]
At the moment the Lambda function in the template is not named giving it a name generated by CloudFormation. 

If you make changes to the function that requires a replacement (such as changing runtime) of the function the name will change and CloudFormation does not allow changes to the ServiceToken for existing CustomResources.

This was a mistake on my behalf early on. Had I named it this would not have been an issue as the function would always have the same name even if it is replaced.

I have placed a feature request with AWS that would allows the ServiceToken to change but I don't think it'll be picked up.

**Comment by carlnordenfelt** [comment]
I also want to add that I'm no longer actively developing this project except for fixing bugs and such. CloudFormation has been updated since it was created and with the RestAPI import functionality they provide pretty much everything needed. For the odd case that they don't, I migrate these CustomResources to the [lulo project](https://carlnordenfelt.github.io/lulo/).

There will come a few ApiGateway plugins to lulo shortly to cover the gaps in CloudFormation.

**Comment by jordie23** [comment]
Thanks for the reply and info!

We currently just use these in cloudformation:

      Custom::ApiBasePathMapping
      Custom::ApiDomainName

If we destroy the stack used to create the custom resource lambda, will this affect the API using these? Will that need to be destroyed and recreated as well ?

**Comment by carlnordenfelt** [comment]
Hi,

If you update the custom resource lambda you will not be able to run updates on the stacks using these resources.
What you can do is remove the resources from the stacks before updating and then re-add them again after with the new service token. This will leave you with a short interruption during the updates but you don't need to tear down the entire stacks.

These particular custom resources are coming to Lulo, hopefully today as a matter of fact. Since these are the only ones you are using I would suggest migrating to Lulo instead as it is a lot more stable and provides a lot more functionality than this project. It is also extendible with new plugins and is being actively maintained. Migrating to Lulo will give you the same interruption though. If you want, I can update this thread when these plugins are available.

I apologise for the inconvenience, this really is caused by a bad choice on my behalf early on :(

**Comment by carlnordenfelt** [comment]
Hi again!

I have just released version 1.0.0 of the [DomainName](https://www.npmjs.com/package/lulo-plugin-apigateway-domain-name) plugin for Lulo.

It brand new and hasn't been battle tested by anyone but myself.
I am currently using this in combination with the built-in CloudFormation [AWS::ApiGateway::BasePathMapping](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-basepathmapping.html) resource and it seems to be working very well so far :)

If these are the only resources you are using from this project I recommend switching to Lulo and native CFN resources instead.
